// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozbzschfxmabpqxhnduy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96YnpzY2hmeG1hYnBxeGhuZHV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MzEwNjksImV4cCI6MjA1ODIwNzA2OX0.vz09PGgAMQEwY6SpoksUhFbMy29wtq7h01G_uOpjKzc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);